<?php

declare(strict_types=1);

namespace Generated;

/**
 * This function is generated by SwitchRoute.
 * Do not modify it manually. Any changes will be overwritten.
 */
function route_generate_function_test_function_ns(string $method, string $path)
{
    $segments = $path === "/" ? [] : explode("/", trim($path, "/"));
    $allowedMethods = [];

    switch ($segments[0] ?? "\0") {
        case "\0":
            $allowedMethods = ['GET'];
            switch ($method) {
                case 'GET':
                    return info();
            }
            break 1;
    }

    return false;
}