<?php

declare(strict_types=1);

/**
 * This function is generated by SwitchRoute.
 * Do not modify it manually. Any changes will be overwritten.
 */
function route_generate_function_test_all_vars(string $method, string $path)
{
    $segments = $path === "/" ? [] : explode("/", trim($path, "/"));
    $allowedMethods = [];

    switch ($segments[0] ?? "\0") {
        default:
            switch ($segments[1] ?? "\0") {
                default:
                    switch ($segments[2] ?? "\0") {
                        default:
                            switch ($segments[3] ?? "\0") {
                                case "\0":
                                    $allowedMethods = ['GET'];
                                    switch ($method) {
                                        case 'GET':
                                            return ["foo" => $segments[0], "bar" => $segments[1], "qux" => $segments[2]];
                                    }
                                    break 4;
                            }
                            break 3;
                    }
                    break 2;
            }
            break 1;
    }

    return false;
}