<?php

declare(strict_types=1);

/**
 * This function is generated by SwitchRoute.
 * Do not modify it manually. Any changes will be overwritten.
 */
function route_generate_function_test_default(string $method, string $path, ?callable $instantiate = null)
{
    $segments = $path === "/" ? [] : explode("/", trim($path, "/"));
    $allowedMethods = [];

    switch ($segments[0] ?? "\0") {
        case "\0":
            $allowedMethods = ['GET'];
            switch ($method) {
                case 'GET':
                    return info();
            }
            break 1;
    }

    http_response_code(404);
    echo "Not Found";
}