<?php

declare(strict_types=1);

/**
 * This function is generated by SwitchRoute.
 * Do not modify it manually. Any changes will be overwritten.
 */
function route_generate_function_test(string $method, string $path)
{
    $segments = $path === "/" ? [] : explode("/", trim($path, "/"));
    $allowedMethods = [];

    switch ($segments[0] ?? "\0") {
        case "\0":
            $allowedMethods = ['GET'];
            switch ($method) {
                case 'GET':
                    return call('InfoController', '', NULL);
            }
            break 1;
        case "users":
            switch ($segments[1] ?? "\0") {
                case "\0":
                    $allowedMethods = ['GET', 'POST'];
                    switch ($method) {
                        case 'GET':
                            return call('UserController', 'listAction', NULL);
                        case 'POST':
                            return call('UserController', 'addAction', NULL);
                    }
                    break 2;
                default:
                    switch ($segments[2] ?? "\0") {
                        case "\0":
                            $allowedMethods = ['GET', 'POST', 'PUT', 'DELETE'];
                            switch ($method) {
                                case 'GET':
                                    return call('UserController', 'getAction', $segments[1]);
                                case 'POST':
                                case 'PUT':
                                    return call('UserController', 'updateAction', $segments[1]);
                                case 'DELETE':
                                    return call('UserController', 'deleteAction', $segments[1]);
                            }
                            break 3;
                        case "photos":
                            switch ($segments[3] ?? "\0") {
                                case "\0":
                                    $allowedMethods = ['GET', 'POST'];
                                    switch ($method) {
                                        case 'GET':
                                            return call('', 'ListPhotosAction', $segments[1]);
                                        case 'POST':
                                            return call('', 'AddPhotosAction', $segments[1]);
                                    }
                                    break 4;
                            }
                            break 3;
                    }
                    break 2;
            }
            break 1;
        case "export":
            switch ($segments[1] ?? "\0") {
                case "\0":
                    $allowedMethods = ['POST'];
                    switch ($method) {
                        case 'POST':
                            return require 'scripts/export.php';
                    }
                    break 2;
            }
            break 1;
    }

    return call('', 'NotFoundAction', $allowedMethods ?? array (
    ));
}